# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/teuvo',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/teuvo',
                'lib_path': 'teuvo'},
  'syms': {'teuvo.core': {'teuvo.core.foo': ('core.html#foo', 'teuvo/core.py')}}}
